#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: '{build}'

# Do not increment build number for pull requests (GitHub only)
pull_requests:
  do_not_increment_build_number: true

# disable publishing of .nupkg artifacts to
# account/project feeds for pull request builds
nuget:
  disable_publish_on_pr: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#
cache:
  - packages
  
# scripts that run after cloning repository
#install:
#  - cmd: choco install dotnetcore-sdk --pre

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

image: Visual Studio 2019

before_build:
  - dotnet --info
  - dotnet restore
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - choco install mssqlserver-compact3.5 --ignore-dependencies

build:
  parallel: true                                    # enable MSBuild parallel builds
  project: DotNetToolkit.Repository.sln             # path to Visual Studio solution or project

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: '**\DotNetToolkit.Repository.*.nupkg'     # find all NuGet packages recursively
    name: NuGet

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:

# Deploying to NuGet feed
- provider: NuGet
  server: https://www.myget.org/F/dotnettoolkitrepository-dev/api/v2/package
  api_key:
    secure: SR7XeaMyomlDy1JekkpUVvPhQ9RnaRmvDZ68gR1S/xFEe1QfYFbsss9GDq0Q/8Rq
  skip_symbols: false
  symbol_server: https://www.myget.org/F/dotnettoolkitrepository-dev/symbols/api/v2/package
  on:
    branch: master                    # release from master branch only
- provider: NuGet
  name: production
  api_key:
    secure: uSU6YGrWfh7Ruar11vqDFOtauPZXzKYFHUp8WoK86wDjT5ahRJXpLqPfusF+oKFd
  skip_symbols: true
  on:
    branch: master                   # release from master branch only
    appveyor_repo_tag: true          # deploy on tag push only
    
# Deploy to GitHub Releases
- provider: GitHub
  auth_token:
      secure: kFfqkCNCS405n1FfAo/51sC5Mff9UR9QBjFfTLHJudNGhhj4X1luHRb6hJEksmQI
  draft: false
  prerelease: false
  on:
    branch: master                   # release from master branch only
    appveyor_repo_tag: true          # deploy on tag push only
    
#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - dotnet test .\test\DotNetToolkit.Repository.Test\DotNetToolkit.Repository.Test.csproj --configuration Release
  - dotnet test .\test\DotNetToolkit.Repository.Integration.Test\DotNetToolkit.Repository.Integration.Test.csproj --configuration Release
